workspace(name = "com_github_fancom_rules_nfpm_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Note: see the README for the latest http_archive details for this repository.
local_repository(
    name = "com_github_fancom_rules_nfpm",
    path = "../",
)

load("@com_github_fancom_rules_nfpm//nfpm:repositories.bzl", "rules_nfpm_dependencies")

rules_nfpm_dependencies()

load("@com_github_fancom_rules_nfpm//nfpm:setup.bzl", "rules_nfpm_setup")

rules_nfpm_setup()

load("@com_github_fancom_rules_nfpm//nfpm:go_repositories.bzl", "rules_nfpm_go_dependencies")

rules_nfpm_go_dependencies()

# Dependencies needed for building the 'helloworld' binary

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "a8d6b1b354d371a646d2f7927319974e0f9e52f73a2452d2b3877118169eb6bb",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.23.3/rules_go-v0.23.3.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.23.3/rules_go-v0.23.3.tar.gz",
    ],
)
